version: "3.7"

services:
  
  product-list:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
    networks:
      - product-list-network

networks:
  product-list-network:
    driver: bridge